name: Python linter

on: [pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.7]
    steps:
      - name: Install dependencies
        run: |
          python -m pip install black
      - name: Black Code Formatter
        run: |
          black . --check
