name: Python package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:

    runs-on: windows-latest
    steps:
    - name: Set up buid environment
      run: |
        choco install -y python --version=3.7.0
        choco install -y vcbuildtools

    - name: Build Pyinstaller
      run: |
        git clone https://github.com/pyinstaller/pyinstaller
        cd pyinstaller
        python ./waf all
        python setup.py install

    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip -r requirements.txt

    - name: Generate version file
      run: |
        python .github/workflows/version_embedd.py > version.txt

    - name: Build as binary
      run: |
        pyinstaller.exe vrc_meta_writer.py --version-file "version.txt" -F
        pyinstaller.exe vrc_meta_reader.py --version-file "version.txt" -F
        pyinstaller.exe user_list_sorter.py --version-file "version.txt" -F
        pyinstaller.exe vrc_meta_editor.py --version-file "version.txt" -F
    - name: Achive to zip
      run: |
        powershell compress-archive -Path dist/vrc_meta_writer.exe,dist/vrc_meta_reader.exe,dist/user_list_sorter.exe,dist/vrc_meta_editor.exe,config.yml,user_list.yml,README.md -DestinationPath dist/vrc_meta_tool.zip
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: "dist/vrc_meta_tool.zip"
        prerelease: ${{ contains(github.ref, '-beta') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
